CREATE TABLE USER (
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   FIRSTNAME VARCHAR(80) NOT NULL,
   LASTNAME VARCHAR(80) NOT NULL,
   MAIL VARCHAR(80) NOT NULL,
   PASSWORD VARCHAR(80) NOT NULL,
   BIRTHDATE DATE NOT NULL,
   CITY	VARCHAR(80) NOT NULL,
   GENDER VARCHAR(20),
   USERTYPE VARCHAR(80) NOT NULL,
   AVATAR VARCHAR(255) 
)